name: Create ZIP Archive

on:
  push:
    paths:
      - '**'  # どのファイルがアップロードされてもトリガーする

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create ZIP archive
      run: |
        zip -r archive.zip .
        ls -l  # ZIPファイルが生成されたことを確認するためにディレクトリ内容を表示

    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: ./archive.zip
